name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/github_actions:latest
        IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
        docker buildx build --push --tag $IMAGE_NAME .

    - name: Verify Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/github_actions:latest
        IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
        docker run $IMAGE_NAME echo "Verify successful"
